name: Sync gh-pages branch

on:
  push:
    branches: 
      - zero

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Setup GPG key
        run: |
          echo "${{ secrets.PGP_PRIVATE_KEY }}" > private.key
          chmod 600 private.key
          gpg --import private.key
