name: Sync gh-pages branch

on:
  push:
    branches: 
      - zero

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      # Runs a single command using the runners shell
      - name: Test
        run: |
          apt update
          apt upgrade -y
          apt install gpg
